# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d65bf74b2ab21094d137879ce826e8e943e1a1046d9acdf73b4f4b7b957a82c81aa61769a3b0bfec8719890464d4579eac5aaecc63d588113c6617046b93241

test:
  secret_key_base: daf3648bc001b30b7fee3ac65b56a606aed70be9b8d91caa96fffbf4b2226fc252bd9dd0b14d9d9a54fe31b95ba6e154204e7524a91a588801ab414e0f591c4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
